### ISSUE TITLE
Complains about AWS SDK version

### ISSUE THREAD

**Issue by ericlafond** [LanceMcCarthy/akeyless-action#135]
(node:2781) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by ericlafond** [comment]
The action is working.  This just made it confusing to where the issue really was.

**Comment by LanceMcCarthy** [comment]
Thanks Eric, this raised the fact that I am not writing tot he console as much as I used to. I will add this back in the next update.

Tracked here => https://github.com/LanceMcCarthy/akeyless-action/issues/136
